#!/bin/bash

#!g++ Starfighter.o -o Starfighter -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio

g++ Starfighter.o Ignition_Engine.o Game_Objects.o Game_physics.o SFML_Tools.o VectorVictor2.o Ignition.o -o Starfighter -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio

exit 0
